import { ApiProperty } from "@nestjs/swagger";
import { AuthUserDto } from "./user-response.dto";

export class AuthResponseDto {
  @ApiProperty({
    description: "JWT token generated by SurrealDB scopes",
    example:
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6InVzZXI6YWJjMTIzIiwiaWF0IjoxNzAxMjM0NTY3LCJleHAiOjE3MDE4MzgzNjd9.sometoken",
  })
  token: string;

  @ApiProperty({
    description: "Token type",
    example: "Bearer",
  })
  tokenType: string;

  @ApiProperty({
    description: "Seconds until the token expires",
    example: 86400,
  })
  expiresIn: number;

  @ApiProperty({
    description: "Authenticated user information",
    type: AuthUserDto,
  })
  user: AuthUserDto;
}
