import type { Cohorte, Student, FrictionPoint, QualitativeTheme, Misconception, Notification } from "@/types/analytics"

export const mockCohortes: Cohorte[] = [
  {
    id: "coh_001",
    nombre: "Cohorte Otoño 2024",
    programa: "Xpertia Emprendedor",
    programa_id: "prog_001",
    fecha_inicio: "2024-09-15",
    fecha_fin: "2024-12-15",
    num_estudiantes: 15,
    progreso_general: 68,
    estado: "activa",
    metricas: {
      tasa_completacion: 73,
      tiempo_promedio_componente: 28,
      score_promedio: 8.2,
      estudiantes_riesgo: 3,
    },
  },
  {
    id: "coh_002",
    nombre: "Cohorte Verano 2024",
    programa: "Xpertia Emprendedor",
    programa_id: "prog_001",
    fecha_inicio: "2024-06-01",
    fecha_fin: "2024-08-30",
    num_estudiantes: 18,
    progreso_general: 100,
    estado: "finalizada",
    metricas: {
      tasa_completacion: 85,
      tiempo_promedio_componente: 32,
      score_promedio: 7.9,
      estudiantes_riesgo: 0,
    },
  },
]

export const mockStudents: Student[] = [
  {
    id: "est_001",
    nombre: "Ana García",
    email: "ana.garcia@example.com",
    avatar: "/avatar-woman-1.png",
    estado: "activo",
    progreso_general: 85,
    componentes_completados: 29,
    componentes_totales: 34,
    score_promedio: 8.7,
    ultima_actividad: "2024-11-03T14:35:00",
    tiempo_total_horas: 52.5,
    componentes: [
      { id: "comp_001", estado: "completado", score: 9.0, tiempo_min: 18 },
      { id: "comp_002", estado: "completado", score: 8.5, tiempo_min: 35 },
      { id: "comp_003", estado: "en_progreso", progreso: 65, tiempo_min: 22 },
      { id: "comp_004", estado: "completado", score: 9.2, tiempo_min: 28 },
      { id: "comp_005", estado: "completado", score: 8.8, tiempo_min: 42 },
      { id: "comp_006", estado: "no_iniciado" },
    ],
  },
  {
    id: "est_002",
    nombre: "Carlos Ruiz",
    email: "carlos.ruiz@example.com",
    avatar: "/avatar-man-1.png",
    estado: "en_riesgo",
    progreso_general: 45,
    componentes_completados: 15,
    componentes_totales: 34,
    score_promedio: 6.8,
    ultima_actividad: "2024-10-25T10:20:00",
    tiempo_total_horas: 28.0,
    alertas: ["Inactivo por 10 días", "Score bajo en simulaciones"],
    componentes: [
      { id: "comp_001", estado: "completado", score: 7.0, tiempo_min: 25 },
      { id: "comp_002", estado: "completado", score: 6.5, tiempo_min: 48 },
      { id: "comp_003", estado: "con_dificultad", score: 5.5, tiempo_min: 65, intentos: 3 },
      { id: "comp_004", estado: "no_iniciado" },
      { id: "comp_005", estado: "no_iniciado" },
      { id: "comp_006", estado: "no_iniciado" },
    ],
  },
  {
    id: "est_003",
    nombre: "María López",
    email: "maria.lopez@example.com",
    avatar: "/avatar-woman-2.png",
    estado: "activo",
    progreso_general: 92,
    componentes_completados: 31,
    componentes_totales: 34,
    score_promedio: 9.1,
    ultima_actividad: "2024-11-04T09:15:00",
    tiempo_total_horas: 48.0,
    componentes: [
      { id: "comp_001", estado: "completado", score: 9.5, tiempo_min: 15 },
      { id: "comp_002", estado: "completado", score: 9.0, tiempo_min: 30 },
      { id: "comp_003", estado: "completado", score: 9.2, tiempo_min: 25 },
      { id: "comp_004", estado: "completado", score: 8.8, tiempo_min: 32 },
      { id: "comp_005", estado: "en_progreso", progreso: 80, tiempo_min: 35 },
      { id: "comp_006", estado: "no_iniciado" },
    ],
  },
  {
    id: "est_004",
    nombre: "Diego Fernández",
    email: "diego.fernandez@example.com",
    avatar: "/avatar-man-2.png",
    estado: "activo",
    progreso_general: 72,
    componentes_completados: 24,
    componentes_totales: 34,
    score_promedio: 8.0,
    ultima_actividad: "2024-11-04T11:20:00",
    tiempo_total_horas: 41.0,
    componentes: [
      { id: "comp_001", estado: "completado", score: 8.0, tiempo_min: 20 },
      { id: "comp_002", estado: "completado", score: 7.8, tiempo_min: 38 },
      { id: "comp_003", estado: "completado", score: 8.2, tiempo_min: 28 },
      { id: "comp_004", estado: "en_progreso", progreso: 45, tiempo_min: 18 },
      { id: "comp_005", estado: "no_iniciado" },
      { id: "comp_006", estado: "no_iniciado" },
    ],
  },
  {
    id: "est_005",
    nombre: "Laura Martínez",
    email: "laura.martinez@example.com",
    avatar: "/avatar-woman-3.png",
    estado: "en_riesgo",
    progreso_general: 38,
    componentes_completados: 13,
    componentes_totales: 34,
    score_promedio: 7.2,
    ultima_actividad: "2024-10-28T16:45:00",
    tiempo_total_horas: 25.5,
    alertas: ["Inactivo por 7 días"],
    componentes: [
      { id: "comp_001", estado: "completado", score: 7.5, tiempo_min: 22 },
      { id: "comp_002", estado: "completado", score: 7.0, tiempo_min: 42 },
      { id: "comp_003", estado: "en_progreso", progreso: 30, tiempo_min: 15 },
      { id: "comp_004", estado: "no_iniciado" },
      { id: "comp_005", estado: "no_iniciado" },
      { id: "comp_006", estado: "no_iniciado" },
    ],
  },
]

export const mockFrictionPoints: FrictionPoint[] = [
  {
    id: "friction_001",
    severidad: "critico",
    componente_id: "comp_012",
    componente_nombre: "Simulación: Entrevista de Discovery Básica",
    estudiantes_impactados: 8,
    estudiantes_totales: 15,
    tasa_abandono: 53,
    tiempo_promedio: 45,
    tiempo_esperado: 30,
    detectado: "2024-11-02T10:00:00",
    analisis_ia:
      "Los estudiantes abandonan después de 3-4 intercambios. Análisis de transcripts muestra que el personaje responde de forma muy escéptica desde el inicio, frustrando a estudiantes novatos.",
    sugerencias: [
      "Ajustar personalidad del personaje a 'cooperativo' en primeros intercambios",
      "Agregar lección previa sobre manejo de objeciones",
    ],
  },
  {
    id: "friction_002",
    severidad: "importante",
    componente_id: "comp_007",
    componente_nombre: "Cuaderno: Formulación de Hipótesis",
    estudiantes_impactados: 12,
    estudiantes_totales: 15,
    tasa_abandono: 0,
    tiempo_promedio: 65,
    tiempo_esperado: 30,
    detectado: "2024-11-01T14:30:00",
    analisis_ia:
      "Estudiantes invierten más del doble del tiempo estimado. Análisis de respuestas muestra confusión entre 'hipótesis de problema' e 'hipótesis de solución'.",
    sugerencias: [
      "Agregar ejemplos diferenciados de ambos tipos de hipótesis",
      "Incluir template guiado con estructura clara",
    ],
  },
  {
    id: "friction_003",
    severidad: "menor",
    componente_id: "comp_015",
    componente_nombre: "Lección: Métricas de Validación",
    estudiantes_impactados: 5,
    estudiantes_totales: 15,
    tasa_abandono: 0,
    tiempo_promedio: 42,
    tiempo_esperado: 35,
    detectado: "2024-10-30T09:15:00",
    analisis_ia:
      "Algunos estudiantes tardan más en la sección de fórmulas estadísticas. No es crítico pero podría mejorarse con ejemplos visuales.",
    sugerencias: ["Agregar infografía explicativa de fórmulas", "Incluir calculadora interactiva"],
  },
]

export const mockQualitativeThemes: QualitativeTheme[] = [
  { tema: "Validación de mercado", frecuencia: 23, sentimiento: "neutral" },
  { tema: "Entrevistas a usuarios", frecuencia: 18, sentimiento: "positivo" },
  { tema: "Análisis competitivo", frecuencia: 12, sentimiento: "neutral" },
  { tema: "Hipótesis de problema", frecuencia: 15, sentimiento: "neutral" },
  { tema: "Métricas cuantitativas", frecuencia: 9, sentimiento: "negativo" },
]

export const mockMisconceptions: Misconception[] = [
  {
    concepto: "Confusión entre validación y verificación",
    frecuencia: 9,
    descripcion:
      "Estudiantes usan ambos términos indistintamente cuando en realidad tienen significados diferentes en el contexto de metodología lean.",
    ejemplos: [
      { texto: "Después de validar que el código funciona...", estudiante: "E1" },
      { texto: "Verificamos que los clientes tienen este problema...", estudiante: "E4" },
      { texto: "La validación técnica del prototipo fue exitosa...", estudiante: "E7" },
    ],
    impacto: {
      score_promedio_afectados: 7.2,
      score_promedio_no_afectados: 8.5,
    },
  },
  {
    concepto: "Hipótesis vs Suposición",
    frecuencia: 6,
    descripcion:
      "Algunos estudiantes no distinguen entre una hipótesis testeable y una simple suposición sin criterios de validación.",
    ejemplos: [
      { texto: "Mi hipótesis es que la app será exitosa...", estudiante: "E2" },
      { texto: "Supongo que los usuarios necesitan esta funcionalidad...", estudiante: "E5" },
    ],
    impacto: {
      score_promedio_afectados: 6.8,
      score_promedio_no_afectados: 8.3,
    },
  },
]

export const mockNotifications: Notification[] = [
  {
    id: "notif_001",
    tipo: "alerta_punto_friccion",
    titulo: "8 estudiantes abandonaron Simulación X",
    timestamp: "2024-11-04T10:30:00",
    leida: false,
    accion: "Ver detalles",
    link: "/cohortes/coh_001#friction",
  },
  {
    id: "notif_002",
    tipo: "estudiante_riesgo",
    titulo: "Carlos Ruiz lleva 10 días inactivo",
    timestamp: "2024-11-04T09:15:00",
    leida: false,
    accion: "Contactar estudiante",
    link: "/cohortes/coh_001/estudiantes/est_002",
  },
  {
    id: "notif_003",
    tipo: "completacion_proof_point",
    titulo: "12 estudiantes completaron CSF Report",
    timestamp: "2024-11-03T16:20:00",
    leida: true,
    accion: "Ver reportes",
  },
  {
    id: "notif_004",
    tipo: "mejora_detectada",
    titulo: "Score promedio de cohorte subió 15%",
    timestamp: "2024-11-03T14:00:00",
    leida: true,
    accion: "Ver métricas",
  },
]
